# Generic sign texts
SignText: "[电梯]"
DefectText: "&k损坏!"
DisabledText: "&c关闭"
MaintenanceText: "&c维护"
UpText: "&a上升"
DownText: "&a下降"

# The change for a lift to get defective. Disabled by default.
DefectRate: 0.0

# The repair item and amount required
RepairItem: REDSTONE
RepairAmount: 5

# The master repair item and amount required
MasterRepairItem: DIAMOND
MasterRepairAmount: 10

# The default speed of a lift
DefaultSpeed: 16

# Create lifts with realistic mode enabled default?
DefaultRealistic: true

# The time for the door to close, in ticks. 20 ticks = 1 sec
DoorCloseTime: 100

# Teleport with packets (no Bukkit events will be fired then)
PacketTeleport: false

# The updater checker - It will check for new versions, and install automatically if found.
UpdateChecker:
  Enabled: false
  DownloadOnUpdate: true